{
 "title": "Starlink Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_INFLUXDB", "label": "InfluxDB DataSource", "query": "InfluxDB-starlinkstats" },
   {
    "name": "TBL_STATS",
    "label": "Table name for Statistics",
    "query": "spacex.starlink.user_terminal.status"
   }
  ]
 },
 "panels": [
  {
   "title": "Current State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       { "params": [ "state" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Software Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       { "params": [ "software_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Obstruction Details (last 12 hours)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.ping_stats",
     "select": [
      [
       {
        "params": [
         "count_full_obstructed_ping_drop"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Obstructed Count" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "count_full_unscheduled_ping_drop"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "No Satellites Count" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spacex.starlink.user_terminal.ping_stats",
     "query": "SELECT abs(mean(\"count_full_ping_drop\") - (mean(\"count_full_obstructed_ping_drop\") + mean(\"count_full_unscheduled_ping_drop\"))) AS \"Obstructed + No Satellites + Beta Downtime\" FROM \"spacex.starlink.user_terminal.ping_stats\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count_full_ping_drop" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "Obstructed + No Satellites + Beta Downtime"
        ],
        "type": "alias"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Obstruction Directions",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 10, "w": 6, "x": 15, "y": 0 },
   "targets": [
    {
     "alias": "0° North",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_0"
        ],
        "type": "field"
       },
       { "params": [ "* 100" ], "type": "math" },
       { "params": [ "0° North" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "30°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_1"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "30°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "60°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_2"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "60°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "90° East",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_3"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "90° East" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "120°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_4"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "120°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "150°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_5"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "150°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "180° South",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_6"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "180° South" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "210°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_7"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "210°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "240°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_8"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "240°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "270° West",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_9"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "270° West" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "300°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_10"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "300°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "330°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_11"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "330°" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Obstruction Direction Percentages",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "0° North",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_0"
        ],
        "type": "field"
       },
       { "params": [ "* 100" ], "type": "math" },
       { "params": [ "0° North" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "30°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_1"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "30°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "60°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_2"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "60°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "90° East",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_3"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "90° East" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "120°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_4"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "120°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "150°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_5"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "150°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "180° South",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_6"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "180° South" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "210°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_7"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "210°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "240°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_8"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "240°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "270° West",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_9"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "270° West" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "300°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_10"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "300°" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "330°",
     "limit": "1",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       {
        "params": [
         "raw_wedges_fraction_obstructed_11"
        ],
        "type": "field"
       },
       { "params": [ "*100" ], "type": "math" },
       { "params": [ "330°" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       { "params": [ "pop_ping_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current SNR",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "SNR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" }
      ],
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Speeds Seen (In given time range)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Top Download Speed:",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Top Upload Speed:",
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Starlink Satellite Tracking Map",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Starlink Connection Drop Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Event" } },
   "targets": [
    {
     "measurement": "spacex.starlink.user_terminal.history",
     "select": [
      [
       { "params": [ "pop_ping_drop_rate" ], "type": "field" },
       { "params": [ "Drop Rate" ], "type": "alias" }
      ],
      [
       { "params": [ "scheduled" ], "type": "field" },
       { "params": [ "Scheduled" ], "type": "alias" }
      ],
      [
       { "params": [ "obstructed" ], "type": "field" },
       { "params": [ "Obstructed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput Over Time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       { "params": [ "downlink_throughput_bps" ], "type": "field" },
       { "params": [ "bps Down" ], "type": "alias" }
      ],
      [
       { "params": [ "uplink_throughput_bps" ], "type": "field" },
       { "params": [ "bps Up" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping Latency vs. SNR",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "SNR", "label": "SNR" }
   ],
   "targets": [
    {
     "measurement": "/^$TBL_STATS$/",
     "select": [
      [
       { "params": [ "snr" ], "type": "field" },
       { "params": [ "*10" ], "type": "math" },
       { "params": [ "SNR" ], "type": "alias" }
      ],
      [
       { "params": [ "pop_ping_latency_ms" ], "type": "field" },
       { "params": [ "Ping Latency" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Alerts & Versions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "measurement": "/^$TBL_STATS$/",
     "query": "SELECT \"state\" AS \"State\", \"currently_obstructed\" AS \"Obstructed\", \"alert_unexpected_location\" AS \"Bad Location\", \"alert_thermal_throttle\" AS \"Temp Throttled\", \"alert_thermal_shutdown\" AS \"Temp Shutdown\", \"alert_motors_stuck\" AS \"Motors Stuck\", \"alert_mast_not_near_vertical\" AS \"Mast not Vertical\", \"alert_slow_ethernet_speeds\" AS \"Slow Ethernet\", \"software_version\" AS \"Software Version\", \"hardware_version\" AS \"Hardware Version\" FROM /^$TBL_STATS$/ WHERE $timeFilter",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       { "params": [ "State" ], "type": "alias" }
      ],
      [
       { "params": [ "currently_obstructed" ], "type": "field" },
       { "params": [ "Obstructed" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_unexpected_location" ], "type": "field" },
       { "params": [ "Bad Location" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_thermal_throttle" ], "type": "field" },
       { "params": [ "Temp Throttled" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_thermal_shutdown" ], "type": "field" },
       { "params": [ "Temp Shutdown" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_motors_stuck" ], "type": "field" },
       { "params": [ "Motors Stuck" ], "type": "alias" }
      ],
      [
       { "params": [ "software_version" ], "type": "field" },
       { "params": [ "Software Version" ], "type": "alias" }
      ],
      [
       { "params": [ "hardware_version" ], "type": "field" },
       { "params": [ "Hardware Version" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_mast_not_near_vertical" ], "type": "field" },
       { "params": [ "Mast not Vertical" ], "type": "alias" }
      ],
      [
       { "params": [ "alert_slow_ethernet_speeds" ], "type": "field" },
       { "params": [ "Slow Ethernet" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}